MODES = {
    "Fotografia": {
        "key": "photo_bg",
        "description": "Usa IA para separar un sujeto real del fondo. Ideal para fotos de personas, productos o autos sin letras alrededor.",
        "use_ai": True,
        "remove_black": False,
        "clean_alpha": True,
        "trim": True,
        "alpha_cut": 70,
        "despeckle_area": 2,
        "edge_contract": 0,
        "black_threshold": 18,
        "protect_details": True,
        "max_ai_side": 1600,
    },
    "PNG Transparente": {
        "key": "transparent_png",
        "description": "No usa IA. Limpia semitransparencias, halos y pixeles basura de un PNG que ya trae transparencia.",
        "use_ai": False,
        "remove_black": False,
        "clean_alpha": True,
        "trim": True,
        "alpha_cut": 65,
        "despeckle_area": 2,
        "edge_contract": 0,
        "black_threshold": 18,
        "protect_details": True,
        "max_ai_side": 1600,
    },
    "Conservar diseno": {
        "key": "preserve_full",
        "description": "No usa IA. Mantiene letras, splash, sombras, fondos y efectos. Usalo cuando no quieres borrar nada del arte.",
        "use_ai": False,
        "remove_black": False,
        "clean_alpha": False,
        "trim": False,
        "alpha_cut": 40,
        "despeckle_area": 1,
        "edge_contract": 0,
        "black_threshold": 18,
        "protect_details": True,
        "max_ai_side": 1800,
    },
    "Fondo negro": {
        "key": "black_bg",
        "description": "Elimina negro casi puro del fondo. Conserva detalles claros, cromados, letras y splash blanco.",
        "use_ai": False,
        "remove_black": True,
        "clean_alpha": True,
        "trim": True,
        "alpha_cut": 35,
        "despeckle_area": 1,
        "edge_contract": 0,
        "black_threshold": 24,
        "protect_details": True,
        "max_ai_side": 1800,
    },
    "Preparar DTF": {
        "key": "dtf_ready",
        "description": "Modo final para impresion: limpia alfa, recorta, prepara PNG/PDF y conserva detalles importantes.",
        "use_ai": False,
        "remove_black": False,
        "clean_alpha": True,
        "trim": True,
        "alpha_cut": 70,
        "despeckle_area": 2,
        "edge_contract": 0,
        "black_threshold": 18,
        "protect_details": True,
        "max_ai_side": 1600,
    },
}
