MODES: dict[str, dict[str, object]] = {
    "Photograph": {
        "key": "photograph",
        "label": "Photograph",
        "description": "Use AI only for real photos: people, products, vehicles, or objects on natural backgrounds.",
        "use_ai": True,
        "remove_black": False,
        "clean_alpha": True,
        "trim": True,
        "alpha_cut": 70,
        "despeckle_area": 2,
        "edge_contract": 0,
        "black_threshold": 24,
        "protect_details": True,
        "max_ai_side": 1600,
    },
    "Transparent PNG": {
        "key": "transparent_png",
        "label": "Transparent PNG",
        "description": "Clean halos and tiny alpha trash from artwork that already has transparency.",
        "use_ai": False,
        "remove_black": False,
        "clean_alpha": True,
        "trim": True,
        "alpha_cut": 65,
        "despeckle_area": 2,
        "edge_contract": 0,
        "black_threshold": 24,
        "protect_details": True,
        "max_ai_side": 1600,
    },
    "Preserve artwork": {
        "key": "preserve_artwork",
        "label": "Preserve artwork",
        "description": "Keep complete art, shadows, smoke, splashes, logos, and background effects.",
        "use_ai": False,
        "remove_black": False,
        "clean_alpha": False,
        "trim": False,
        "alpha_cut": 40,
        "despeckle_area": 1,
        "edge_contract": 0,
        "black_threshold": 24,
        "protect_details": True,
        "max_ai_side": 1800,
    },
    "Remove black background": {
        "key": "black_bg",
        "label": "Remove black background",
        "description": "Remove pure background black while preserving black outlines, letters, and shadows.",
        "use_ai": False,
        "remove_black": True,
        "clean_alpha": True,
        "trim": True,
        "alpha_cut": 35,
        "despeckle_area": 1,
        "edge_contract": 0,
        "black_threshold": 24,
        "protect_details": True,
        "max_ai_side": 1800,
    },
    "Dark artwork": {
        "key": "dark_artwork",
        "label": "Dark artwork",
        "description": "Conservative cleanup for dark DTF designs, smoke, chrome, and splash effects.",
        "use_ai": False,
        "remove_black": True,
        "clean_alpha": True,
        "trim": True,
        "alpha_cut": 30,
        "despeckle_area": 1,
        "edge_contract": 0,
        "black_threshold": 18,
        "protect_details": True,
        "max_ai_side": 1800,
    },
    "Prepare for DTF": {
        "key": "dtf_ready",
        "label": "Prepare for DTF",
        "description": "Final print prep with clean alpha, trim, PNG/PDF/ZIP export, and 300 DPI metadata.",
        "use_ai": False,
        "remove_black": False,
        "clean_alpha": True,
        "trim": True,
        "alpha_cut": 70,
        "despeckle_area": 2,
        "edge_contract": 0,
        "black_threshold": 24,
        "protect_details": True,
        "max_ai_side": 1600,
    },
}
