MODES = {
    "Quitar fondo de fotografía": {
        "description": "Usa IA para separar persona/producto/vehículo del fondo. No usar si quieres conservar letras, splash o fondos decorativos.",
        "use_ai": True,
        "skip_if_transparent": True,
        "clean_alpha": True,
        "remove_black": False,
        "trim": True,
        "alpha_cut": 70,
        "despeckle_area": 2,
        "edge_contract": 0,
        "max_ai_side": 1600,
    },
    "Limpiar PNG transparente": {
        "description": "Para archivos que ya vienen sin fondo. Limpia semitransparencias, halos y pixeles basura sin usar IA.",
        "use_ai": False,
        "skip_if_transparent": True,
        "clean_alpha": True,
        "remove_black": False,
        "trim": True,
        "alpha_cut": 70,
        "despeckle_area": 2,
        "edge_contract": 0,
        "max_ai_side": 1600,
    },
    "Conservar diseño completo": {
        "description": "Mantiene letras, splash, sombras, fondo decorativo y todos los efectos. No quita fondo con IA.",
        "use_ai": False,
        "skip_if_transparent": True,
        "clean_alpha": False,
        "remove_black": False,
        "trim": False,
        "alpha_cut": 40,
        "despeckle_area": 1,
        "edge_contract": 0,
        "max_ai_side": 1800,
    },
    "Quitar fondo negro": {
        "description": "Elimina fondo negro conectado a los bordes. Conserva mejor letras y diseño que la IA cuando el fondo es negro sólido.",
        "use_ai": False,
        "skip_if_transparent": True,
        "clean_alpha": True,
        "remove_black": True,
        "trim": True,
        "alpha_cut": 45,
        "despeckle_area": 2,
        "edge_contract": 0,
        "black_threshold": 45,
        "black_tolerance": 22,
        "max_ai_side": 1800,
    },
    "Preparar para DTF": {
        "description": "Modo general de producción: limpia transparencia, recorta, ajusta medida y exporta PNG/PDF a 300 DPI.",
        "use_ai": False,
        "skip_if_transparent": True,
        "clean_alpha": True,
        "remove_black": False,
        "trim": True,
        "alpha_cut": 85,
        "despeckle_area": 4,
        "edge_contract": 0,
        "max_ai_side": 1600,
    },
}
